name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build Docker image
      run: docker build -t playwright-tests .
    - name: Run Playwright tests on Docker
      run: docker run --name playwright-tests -v $(pwd)/playwright-reports:/app/playwright-reports:rw playwright-tests
    - name: Echo PWD
      run: ls
    - name: echo ws
      run: echo '${{ github.workspace }}'
    - name: Copy Playwright reports
      run: sudo docker cp playwright-tests:/app/playwright-reports/ ${{ github.workspace }}/
      
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: '${{ github.workspace }}/playwright-reports'
        retention-days: 30
